'use client';

import { useState, useRef, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import Reel from './Reel';
import AddToPlaylistSheet from '@/components/AddToPlaylistSheet';

export default function ReelFeed({ tracks, intentSummary, loadMoreTracks }: any) {
  const containerRef = useRef<HTMLDivElement>(null);
  const [activeReelIndex, setActiveReelIndex] = useState(0);
  const [showAddSheetForTrack, setShowAddSheetForTrack] = useState<any>(null);
  const [embedController, setEmbedController] = useState<any>(null);
  
  const [savingPlaylist, setSavingPlaylist] = useState(false);
  const [playlistSavedUrl, setPlaylistSavedUrl] = useState<string | null>(null);

  // Swipe Memory Tracking
  const startTimeRef = useRef<number>(Date.now());
  const prevReelIndexRef = useRef<number>(0);

  const saveMemory = (track: any, type: 'likes' | 'skips') => {
      try {
          const artistName = track.artists?.[0]?.name;
          if (!artistName) return;
          
          const memoryStr = localStorage.getItem('pulse_memory');
          const memory = memoryStr ? JSON.parse(memoryStr) : { likes: [], skips: [] };
          
          // Avoid duplicates
          if (memory[type].includes(artistName)) return;
          
          memory[type].push(artistName);
          
          // Cap at 10 items
          if (memory[type].length > 10) {
              memory[type].shift();
          }
          
          localStorage.setItem('pulse_memory', JSON.stringify(memory));
      } catch (err) {
          console.error("Failed to save pulse memory", err);
      }
  };

  const handleDislike = (track: any, index: number) => {
      saveMemory(track, 'skips');
      
      // Auto-scroll to next reel
      const container = containerRef.current;
      if (container) {
          const nextIndex = index + 1;
          if (nextIndex < tracks.length) {
              container.scrollTo({
                  top: nextIndex * container.clientHeight,
                  behavior: 'smooth'
              });
          }
      }
  };

  const handleSavePulse = async () => {
    if (savingPlaylist || tracks.length === 0) return;
    setSavingPlaylist(true);
    try {
        const uris = tracks.map((t: any) => t.uri);
        const res = await fetch('/api/save-playlist', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                name: intentSummary || 'My Vibe',
                description: 'Generated by Pulse',
                uris
            })
        });
        const data = await res.json();
        if (data.error) throw new Error(data.error);
        if (data.playlist_url) {
            setPlaylistSavedUrl(data.playlist_url);
            setTimeout(() => setPlaylistSavedUrl(null), 5000); // Hide toast after 5s
        }
    } catch (err: any) {
        alert(err.message || 'Failed to save playlist');
    } finally {
        setSavingPlaylist(false);
    }
  };

  // Initialize Spotify IFrame API
  useEffect(() => {
    const script = document.createElement("script");
    script.src = "https://open.spotify.com/embed/iframe-api/v1";
    script.async = true;
    document.body.appendChild(script);

    (window as any).onSpotifyIframeApiReady = (IFrameAPI: any) => {
      const element = document.getElementById('spotify-player');
      if (!element) return;
      
      const options = {
        uri: tracks[0]?.uri || '',
        width: '100%',
        height: '152',
        theme: '0' // Dark mode
      };
      
      IFrameAPI.createController(element, options, (controller: any) => {
        setEmbedController(controller);
      });
    };

    return () => {
      if (document.body.contains(script)) {
        document.body.removeChild(script);
      }
      delete (window as any).onSpotifyIframeApiReady;
    };
  }, []); // Only run once on mount

  // Handle active reel change and implicit memory
  useEffect(() => {
    if (activeReelIndex !== prevReelIndexRef.current) {
        // Calculate time spent on previous reel
        const timeSpentMs = Date.now() - startTimeRef.current;
        const prevTrack = tracks[prevReelIndexRef.current];
        
        if (prevTrack) {
            if (timeSpentMs > 15000) {
                // Listened for > 15s (Implicit Like)
                saveMemory(prevTrack, 'likes');
            } else if (timeSpentMs < 3000) {
                // Scrolled past in < 3s (Implicit Skip/Dislike)
                saveMemory(prevTrack, 'skips');
            }
        }
        
        // Reset tracking for new reel
        prevReelIndexRef.current = activeReelIndex;
        startTimeRef.current = Date.now();
    }

    if (embedController && tracks[activeReelIndex]) {
      embedController.loadUri(tracks[activeReelIndex].uri);
      
      // We attempt to play, though browsers may block the first attempt
      // until the user interacts with the iframe.
      // We use a slight timeout to ensure the URI has loaded.
      setTimeout(() => {
          embedController.play();
      }, 500);
    }
  }, [activeReelIndex, embedController, tracks]);

  // Handle scrolling
  useEffect(() => {
    const container = containerRef.current;
    if (!container) return;

    const handleScroll = () => {
      const { scrollTop, clientHeight, scrollHeight } = container;
      // Calculate which reel is mostly in view
      const index = Math.round(scrollTop / clientHeight);
      
      if (index !== activeReelIndex) {
        setActiveReelIndex(index);
      }

      // Trigger load more when user is near the end
      if (scrollHeight - scrollTop - clientHeight < clientHeight * 3) {
          if (loadMoreTracks) loadMoreTracks();
      }
    };

    container.addEventListener('scroll', handleScroll, { passive: true });
    return () => container.removeEventListener('scroll', handleScroll);
  }, [loadMoreTracks, activeReelIndex]);

  return (
    <>
      <div 
        ref={containerRef}
        className="h-full w-full overflow-y-scroll snap-y snap-mandatory bg-black relative"
      >
        {tracks.map((track: any, index: number) => (
          <Reel 
            key={track.id + index} 
            track={track} 
            isActive={index === activeReelIndex} 
            onAddClick={() => setShowAddSheetForTrack(track)}
            onDislike={() => handleDislike(track, index)}
          />
        ))}
      </div>

      {/* Global Spotify Player fixed at the bottom */}
      <div className="absolute bottom-[72px] left-0 w-full px-4 pb-4 pt-12 z-20 pointer-events-none flex flex-col justify-end bg-gradient-to-t from-black via-black/80 to-transparent h-48">
        <div className="pointer-events-auto rounded-xl shadow-spotify-heavy overflow-hidden bg-spotify-surface">
            <div id="spotify-player"></div>
        </div>
      </div>

      {/* Floating Header */}
      <div className="absolute top-0 left-0 w-full p-4 z-30 flex justify-between items-center pointer-events-none pt-8">
        <div className="bg-black/50 backdrop-blur-md px-4 py-2 rounded-full pointer-events-auto">
            <h1 className="text-white font-bold text-sm tracking-widest uppercase flex items-center gap-2">
                <div className="w-2 h-2 bg-spotify-green rounded-full animate-pulse"></div>
                Pulse
            </h1>
        </div>

        <button 
            onClick={handleSavePulse}
            disabled={savingPlaylist}
            className="pointer-events-auto bg-spotify-green text-black px-4 py-2 rounded-full font-bold text-xs uppercase tracking-wider shadow-lg hover:scale-105 active:scale-95 transition-transform"
        >
            {savingPlaylist ? 'Saving...' : playlistSavedUrl ? 'Saved!' : 'Save Pulse'}
        </button>
      </div>

      <AnimatePresence>
        {playlistSavedUrl && (
            <motion.div 
                initial={{ opacity: 0, y: -20 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -20 }}
                className="absolute top-24 left-1/2 -translate-x-1/2 z-40 bg-spotify-elevated border border-spotify-green p-4 rounded-xl shadow-spotify-heavy text-center pointer-events-auto w-[90%] max-w-sm"
            >
                <p className="text-white font-bold mb-2">Playlist Created!</p>
                <a href={playlistSavedUrl} target="_blank" rel="noreferrer" className="text-spotify-green hover:underline text-sm font-semibold">
                    Open in Spotify App
                </a>
            </motion.div>
        )}

        {showAddSheetForTrack && (
          <AddToPlaylistSheet 
            track={showAddSheetForTrack} 
            onClose={() => setShowAddSheetForTrack(null)} 
          />
        )}
      </AnimatePresence>
    </>
  );
}
