import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '../auth/[...nextauth]/route';

export async function POST(req: NextRequest) {
  try {
    const session = await getServerSession(authOptions);
    // @ts-ignore
    const accessToken = session?.accessToken;

    if (!accessToken) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { name, description, uris } = await req.json();

    if (!name || !uris || uris.length === 0) {
        return NextResponse.json({ error: 'Missing required fields' }, { status: 400 });
    }

    // 1. Get User ID
    console.log("Fetching user profile...");
    const meRes = await fetch("https://api.spotify.com/v1/me", {
        headers: { Authorization: `Bearer ${accessToken}` }
    });
    if (!meRes.ok) {
        const errText = await meRes.text();
        console.error("Failed to get user profile:", errText);
        throw new Error(`Failed to get user profile: ${errText}`);
    }
    const meData = await meRes.json();
    const userId = meData.id;
    console.log("Got user ID:", userId);

    // 2. Create Playlist
    const createRes = await fetch(`https://api.spotify.com/v1/users/${encodeURIComponent(userId)}/playlists`, {
        method: "POST",
        headers: { 
            Authorization: `Bearer ${accessToken}`,
            "Content-Type": "application/json"
        },
        body: JSON.stringify({
            name: `Pulse: ${name}`,
            description: description || "Generated by Pulse",
            public: false
        })
    });
    if (!createRes.ok) {
        const errText = await createRes.text();
        console.error("Create playlist error:", errText);
        throw new Error(`Failed to create playlist: ${errText}`);
    }
    const playlistData = await createRes.json();
    const playlistId = playlistData.id;

    // 3. Add Tracks
    const addRes = await fetch(`https://api.spotify.com/v1/playlists/${playlistId}/tracks`, {
        method: "POST",
        headers: { 
            Authorization: `Bearer ${accessToken}`,
            "Content-Type": "application/json"
        },
        body: JSON.stringify({ uris })
    });
    if (!addRes.ok) {
        const errText = await addRes.text();
        console.error("Add tracks error:", errText);
        throw new Error(`Failed to add tracks to playlist: ${errText}`);
    }

    return NextResponse.json({ 
        success: true, 
        playlist_url: playlistData.external_urls?.spotify 
    });

  } catch (error: any) {
    console.error("Save playlist error:", error);
    return NextResponse.json({ error: error.message || 'Failed to save playlist' }, { status: 500 });
  }
}
